# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY src ./src

# Build the project
RUN npm run build

# Use a smaller base image for the final build
FROM node:18-alpine AS release

# Set working directory
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/build ./build

# Copy package.json for runtime dependencies
COPY package.json ./

# Install production dependencies
RUN npm ci --omit=dev

# Set environment variables (adjust as necessary)
ENV COSENSE_PROJECT_NAME=your_project_name
ENV COSENSE_SID=your_sid

# Command to run the server
CMD ["node", "build/index.js"]
